before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: SKfesCHb4ENXCpOwpkEX7F/z4xN7KeiMNzUuq9TtzIP5c9EkqG/vhop7JNTyWpcOqOMf54vTRJkCc+Kn6bDuGCRfrKOEQiA0HBabLsedRQsgX+LogLzT4frHjQz3dqADIwyRpEOy1WPkoIri2XKzYCwkFIbWiuw36llSvkgf7uCDxOxrwd7pk3nozAlNh6TdfOJMhoyVBYv6So3BboanzlOrhbbFYRKlNQ5X8ZCzFybhGAjB5VdHNKCcS9C3vD0lGa3yk45LByR93faegwj8K4zCVNDfmaJeY6EbStN6w6GTi8+66aGmAIVxXUE3fZk80WK4HxSLzjtELbKX1M5oPawmVEeLZM2XZg7EPF2ViNdxbkzf/58ORL/aGmKRJUIt8VNFzrE9FnICd2e8I2KM+cVg1QKSPzW+7WcIHn+NsTJDM6PIPKmh3yLYluw6qTpYxhZC08yQjdKZHwxHpQjIpyufzboVk0cpnE7XhWyxoAWNr6ZeAOc2Knmj/zIAKQK+0YnrGzmzcC4F15ZtlCI5JbZMWaZTkOu87dXVd2eAsY4l4TkIOrXdXD1q2y2Mb4y26mC5ERIzvWbNTLZKFTlHv4MZuRVABNmsbq/d9uM+Z506o4fwkwAmq1ApflxG14wzORMT04Gj3SLWms65IyI5Yk3yaW3jLAzgSpt5hwQ2zvA= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
